
name: "Coding Standards"

on: ["pull_request", "push"]

jobs:
  coding-standards:
    name: "Coding Standards"
    uses: "doctrine/.github/.github/workflows/coding-standards.yml@1.1.1"
    with:
      php-version: "7.4"
